package br.com.spotileo.principal;

import br.com.spotileo.modelos.Musica;
//import br.com.spotileo.modelos.Audio;
import br.com.spotileo.modelos.Podcast;

public class Main {
    public static void main(String[] args) {
        
        Musica novaMusica = new Musica();

        novaMusica.setTitulo("Alive");
        novaMusica.setArtista("Pearl Jam");
        novaMusica.setAlbum("Ten");
        novaMusica.setGenero("Grunge");
        novaMusica.curtir();
        novaMusica.curtir();     
        novaMusica.curtir();
        novaMusica.curtir(); 
        novaMusica.curtir();  
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.curtir(); 
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.reproduzir();
        novaMusica.classifica();
        novaMusica.exibeMusica();

        Podcast novoPodcast = new Podcast();

        novoPodcast.setTitulo("Hipster Ponto Tech!");
        novoPodcast.setApresentador("Alura");
        novoPodcast.setDescricao("Java e Orientação a Objetos!");
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.curtir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.reproduzir();
        novoPodcast.classifica();
        novoPodcast.exibePodcast();
    }    
}
